### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by imgarylai** [DisruptiveAngels/administrate-field-json-to-table#1]
I have tested it on Rails 6 and It works!

https://github.com/valiot/administrate-field-json-to-table/blob/49db1dbfe65826bb2412c1b9763a58241459b699/administrate-field-jsontable.gemspec#L18

Would you be able to make it support Rails 6? 

Thank you.

**Comment by acrogenesis** [comment]
Thanks @imgarylai I've updated the gempsec and released a new version
